# Generated by Django 5.0.14 on 2026-02-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parrain_chauffeur_id', models.IntegerField(help_text='ID du chauffeur parrain (MySQL)')),
                ('recrue_chauffeur_id', models.IntegerField(help_text='ID du chauffeur recruté (MySQL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('parrain_chauffeur_id', 'recrue_chauffeur_id')},
            },
        ),
    ]
