# Generated by Django 5.0.14 on 2026-01-31 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('monthly_target', models.PositiveIntegerField(default=100)),
                ('level', models.CharField(default='Brand Ambassador', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ba_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
