# Generated by Django 5.0.14 on 2026-02-09 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_chauffeurs_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetraitCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ba_email', models.CharField(help_text='Email du BA (lien avec MySQL)', max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telephone_retrait', models.CharField(max_length=30)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('EN_COURS', 'En cours'), ('PAYÉ', 'Payé'), ('REJETÉ', 'Rejeté')], default='PENDING', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxiProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('chauffeur_id', models.IntegerField(blank=True, help_text='FK vers chauffeurs MySQL', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taxi_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
