# Generated by Django 5.0.14 on 2026-02-13 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ba_recruits_target', models.IntegerField(default=12)),
                ('ba_activation_target', models.IntegerField(default=60, help_text='% minimum')),
                ('ba_min_passengers', models.IntegerField(default=10)),
                ('ba_commission_per_recruit', models.IntegerField(default=5000)),
                ('ba_bonus_streak3', models.IntegerField(default=3000)),
                ('ba_bonus_streak7', models.IntegerField(default=8000)),
                ('ba_bonus_top', models.IntegerField(default=15000)),
                ('ba_period', models.CharField(default='mensuel', max_length=20)),
                ('drv_min_trips_week', models.IntegerField(default=15)),
                ('drv_min_rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('drv_max_cancel_rate', models.IntegerField(default=10, help_text='%')),
                ('drv_min_ontime_rate', models.IntegerField(default=85, help_text='%')),
                ('drv_min_passengers_week', models.IntegerField(default=5)),
                ('drv_bonus_active', models.IntegerField(default=2000)),
                ('drv_period', models.CharField(default='hebdomadaire', max_length=20)),
                ('tiers_json', models.JSONField(blank=True, default=list, help_text='Liste des paliers commission')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Objectifs',
                'verbose_name_plural': 'Configuration Objectifs',
            },
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='manager', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
